# Generated by Django 4.0.3 on 2022-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('num_de_la_suerte', models.IntegerField(verbose_name='num_de_la_suerte')),
                ('nacimiento', models.DateField(max_length=50, verbose_name='nacimiento')),
            ],
        ),
    ]
